import { images } from '@/assets';

export const events = [
  {
    id: 1,
    date: {
      day: '25',
      month: 'MAY',
      year: '2026',
      weekday: 'Sat',
      time: '19:00',
      period: 'PM',
    },
    image: images.avatar1,
    tag: 'CONCERT',
    title: 'Martin Garrix Live in Bangkok 2024',
    location: 'Impact Arena, Bangkok',
    price: 89000,
    rating: 4.8,
    reviewCount: 1250,
  },
  {
    id: 2,
    date: {
      day: '08',
      month: 'JUN',
      year: '2026',
      weekday: 'Sat',
      time: '16:00',
      period: 'PM',
    },
    image: images.avatar2,
    tag: 'FESTIVAL',
    title: 'Summer Vibes Music Festival',
    location: 'Ocean Park, Miami',
    price: 129000,
    rating: 4.5,
    reviewCount: 840,
  },
  {
    id: 3,
    date: {
      day: '15',
      month: 'JUN',
      year: '2026',
      weekday: 'Mon',
      time: '20:00',
      period: 'PM',
    },
    image: images.avatar3,
    tag: 'CONCERT',
    title: 'The Weeknd After Hours Tour',
    location: 'SoFi Stadium, Los Angeles',
    price: 199000,
    rating: 4.9,
    reviewCount: 3100,
  },
  {
    id: 4,
    date: {
      day: '22',
      month: 'JUN',
      year: '2026',
      weekday: 'Mon',
      time: '14:00',
      period: 'PM',
    },
    image: images.avatar4,
    tag: 'FESTIVAL',
    title: 'Ultra Music Festival 2024',
    location: 'Bayfront Park, Miami',
    price: 159000,
    rating: 4.7,
    reviewCount: 5200,
  },
  {
    id: 5,
    date: {
      day: '30',
      month: 'JUN',
      year: '2026',
      weekday: 'Tue',
      time: '09:00',
      period: 'AM',
    },
    image: images.avatar5,
    tag: 'SPORTS',
    title: 'NBA Finals Game 7 Live',
    location: 'Chase Center, San Francisco',
    price: 249000,
    rating: 4.9,
    reviewCount: 15600,
  },
  {
    id: 6,
    date: {
      day: '05',
      month: 'JUL',
      year: '2026',
      weekday: 'Sun',
      time: '18:30',
      period: 'PM',
    },
    image: images.home,
    tag: 'CONCERT',
    title: 'Coldplay Music of the Spheres',
    location: 'Wembley Stadium, London',
    price: 179000,
    rating: 5.0,
    reviewCount: 42800,
  },
  // --- Thêm 6 item mới ---
  {
    id: 7,
    date: {
      day: '12',
      month: 'JUL',
      year: '2026',
      weekday: 'Sun',
      time: '10:00',
      period: 'AM',
    },
    image: images.avatar1,
    tag: 'WORKSHOP',
    title: 'Creative UI/UX Design Workshop',
    location: 'Tech Hub, Singapore',
    price: 45000,
    rating: 4.6,
    reviewCount: 320,
  },
  {
    id: 8,
    date: {
      day: '20',
      month: 'JUL',
      year: '2026',
      weekday: 'Mon',
      time: '19:30',
      period: 'PM',
    },
    image: images.avatar2,
    tag: 'THEATRE',
    title: 'The Phantom of the Opera',
    location: 'Majestic Theatre, New York',
    price: 155000,
    rating: 4.9,
    reviewCount: 8900,
  },
  {
    id: 9,
    date: {
      day: '02',
      month: 'AUG',
      year: '2026',
      weekday: 'Sun',
      time: '17:00',
      period: 'PM',
    },
    image: images.avatar3,
    tag: 'SPORTS',
    title: 'Premier League: MU vs Liverpool',
    location: 'Old Trafford, Manchester',
    price: 320000,
    rating: 4.8,
    reviewCount: 25400,
  },
  {
    id: 10,
    date: {
      day: '14',
      month: 'AUG',
      year: '2026',
      weekday: 'Fri',
      time: '21:00',
      period: 'PM',
    },
    image: images.avatar4,
    tag: 'NIGHTLIFE',
    title: 'Techno Night with Charlotte de Witte',
    location: 'Berghain, Berlin',
    price: 65000,
    rating: 4.7,
    reviewCount: 1100,
  },
  {
    id: 11,
    date: {
      day: '25',
      month: 'AUG',
      year: '2026',
      weekday: 'Tue',
      time: '08:30',
      period: 'AM',
    },
    image: images.avatar5,
    tag: 'CONFERENCE',
    title: 'Global AI & Web3 Summit',
    location: 'Dubai Civic Center, UAE',
    price: 500000,
    rating: 4.4,
    reviewCount: 2100,
  },
  {
    id: 12,
    date: {
      day: '05',
      month: 'SEP',
      year: '2026',
      weekday: 'Sat',
      time: '15:00',
      period: 'PM',
    },
    image: images.home,
    tag: 'FESTIVAL',
    title: 'Autumn Food & Wine Festival',
    location: 'Napa Valley, California',
    price: 95000,
    rating: 4.3,
    reviewCount: 650,
  },
];

export const eventData = {
  events: events,
  pagination: {
    totalItems: events.length,
    itemsPerPage: 6,
    currentPage: 1,
    totalPages: Math.ceil(events.length / 6),
    hasNextPage: true,
    hasPrevPage: false,
  },
};
