import { Router } from "express";
import healthRouter from "./health.route";
import authRouter from "./auth.route";
import userRouter from "./user.route";
import couponRouter from "./coupon.route";
import categoryRouter from "./category.route";
import eventRouter from "./event.route";
import ticketRouter from "./ticket.route";
import ticketTypeRouter from "./ticket-type.route";
import seatRouter from "./seat.route";
import orderRouter from "./order.route";
import artistRouter from "./artist.route";
import searchRouter from "./search.route";
import blogCategoryRouter from "./blog_category.route";
import blogRouter from "./blog.route";
import paymentRouter from "./payment.route";
import likeEventRouter from "./like-event.routes";
import saveEventRouter from "./save-event.routes";
import uploadRouter from "./upload.route";
import commentRoute from "./comment.routes";
import contactRouter from "./contact.routes";
import dashboardRouter from "./dashboard.route";
import paymentTransactionRouter from "./payment-transaction.route";
import checkInRouter from "./check-in.route";
import aiBlogIdeaRouter from "./blog-idea.routes";
import aiContentConfigRouter from "./ai-content-config.routes";
import appSettingRouter from "./app-setting.route";
import notificationRoute from "./notification.route";
import refundRoute from "./refund.route";
import aiChatRouter from "./aiChat.route";

const router = Router();

router.use("/health", healthRouter);
router.use("/auth", authRouter);
router.use("/users", userRouter);
router.use("/coupons", couponRouter);
router.use("/categories", categoryRouter);
router.use("/events", eventRouter);
router.use("/tickets", ticketRouter);
router.use("/ticket-types", ticketTypeRouter);
router.use("/seats", seatRouter);
router.use("/orders", orderRouter);
router.use("/payment", paymentRouter);
router.use("/artists", artistRouter);
router.use("/search", searchRouter);
router.use("/blog-categories", blogCategoryRouter);
router.use("/blogs", blogRouter);
router.use("/like-events", likeEventRouter);
router.use("/save-events", saveEventRouter);
router.use("/uploads", uploadRouter);
router.use("/comments", commentRoute);
router.use("/contacts", contactRouter);
router.use("/admin/dashboard", dashboardRouter);
router.use("/payment-transactions", paymentTransactionRouter);
router.use("/check-ins", checkInRouter);
router.use("/blog-ideas", aiBlogIdeaRouter);
router.use("/ai-content-config", aiContentConfigRouter);
router.use("/app-settings", appSettingRouter);
router.use("/notifications", notificationRoute);
router.use("/refunds", refundRoute);
router.use("/ai-chat", aiChatRouter);

export default router;
