import { images } from '@/assets';

export const events = [
  {
    id: 1,
    date: { day: '25', month: 'MAY' },
    image: images.avatar1,
    tag: 'CONCERT',
    title: 'Martin Garrix Live in Bangkok 2024',
    location: 'Impact Arena, Bangkok',
    price: 89000,
  },
  {
    id: 2,
    date: { day: '08', month: 'JUN' },
    image: images.avatar2,
    tag: 'FESTIVAL',
    title: 'Summer Vibes Music Festival',
    location: 'Ocean Park, Miami',
    price: 129000,
  },
  {
    id: 3,
    date: { day: '15', month: 'JUN' },
    image: images.avatar3,
    tag: 'CONCERT',
    title: 'The Weeknd After Hours Tour',
    location: 'SoFi Stadium, Los Angeles',
    price: 199000,
  },
  {
    id: 4,
    date: { day: '22', month: 'JUN' },
    image: images.avatar4,
    tag: 'FESTIVAL',
    title: 'Ultra Music Festival 2024',
    location: 'Bayfront Park, Miami',
    price: 159000,
  },
  {
    id: 5,
    date: { day: '30', month: 'JUN' },
    image: images.avatar5,
    tag: 'SPORTS',
    title: 'NBA Finals Game 7 Live',
    location: 'Chase Center, San Francisco',
    price: 249000,
  },
  {
    id: 6,
    date: { day: '05', month: 'JUL' },
    image: images.home,
    tag: 'CONCERT',
    title: 'Coldplay Music of the Spheres',
    location: 'Wembley Stadium, London',
    price: 179000,
  },
];
