-- AlterTable
ALTER TABLE `system_jobs` MODIFY `type` ENUM('SEND_VERIFY_EMAIL', 'SEND_FORGOT_PASSWORD_EMAIL', 'SEND_EVENT_REMINDER_EMAIL', 'SEND_TICKET_AFTER_PAYMENT_EMAIL', 'SEND_REFUND_REQUEST_RECEIVED_EMAIL', 'SEND_REFUND_RESULT_EMAIL') NOT NULL;
